version: '3'
services:
  redditKeywordBot:
    image: drcarrot/reddit-keyword-bot:latest
    restart: unless-stopped
    environment:
     - BOT_CONFIG_PATH=/config/config.yaml
    volumes:
     - data:/config
